### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by yory8** [yory8/clipman#31]
Version 2 will be a major breaking change, moving from Go to Rust in order to interact with the clipboard directly (through the library wl-clipboard-rs). This will give us full control, allowing us to implement new important features that currently require hacks, or are downright impossible.

Development is happening on the v2 branch. All feedback and help is welcome!

## Major blockers
 
- [ ] fix major bugs
  - [ ] some programs freeze clipman when asking their offer (ie firefox): blocked on https://github.com/YaLTeR/wl-clipboard-rs/issues/6 (?)
  - [ ] clipman watch crashes wayland after a while
- [ ] event-driven query of available offers: blocked on https://github.com/YaLTeR/wl-clipboard-rs/issues/5
- [ ] change history format
  - [ ] decouple index from actual contents: #29
  - [ ] add version of index format to the index
  - [X] explore using a binary format for the index: we now use cbor
- [X] support multiple mime-types at once : #22 

## Minor blockers

- [x] replace `--tool STDOUT` with `clipman export` to export the index as json
- [ ] allow optional notification of errors through notify-send
- [X] drop X tools (dmenu, rofi)
- [X] merge `clipman restore` into `clipman watch`
- [ ] primary clipboard support
- [ ] custom selectors

## Code quality

- [ ] better errors
- [ ] optimize code
- [ ] test!

**Comment by sentriz** [comment]
would it make sense to have the user provide their own tool via pipes?
instead of `clipman pick -t dmenu`, something like 
`clipman hist | my_custom_picker --arg | clipman pick`. because currently there no option for a custom picker

**Comment by yory8** [comment]
@sentriz there is! it's `clipman pick --tool=STDOUT | custom_picker | wl-copy`; it will output the history, newline-separated (with literal newlines escaped, you'll have to take care of it); I might add an option to output json, but for that you can simply query the database itself (at least for now that it's still stored as json).

**Comment by yory8** [comment]
@sentriz 1.5.0 adds support for custom pickers!

**Comment by sentriz** [comment]
Oooh nice! Thank you very much

**Comment by Kommynct** [comment]
Have you released the code elsewhere somewhere or is it just not available yet?

**Comment by yory8** [comment]
@Kommynct it's here in the [v2](https://github.com/yory8/clipman/tree/v2) branch. However, it's stalled; the underlying rust library doesn't have some critical functionality we need, and I don't have the time (and skill) to implement it myself.

Also, I've been wondering wether supporting multiple mime types (issue #22 , the main reason behind the v2 branch) is feasible at all. I mean, copy an image in firefox: wl-paste reports **19** mime types offered; while most of them probably serve the same content, we still need to check and steal every single one of them... I fear it will be too expensive.

**Comment by yory8** [comment]
See https://github.com/yory8/clipman/issues/43#issuecomment-687583506 for important info on how to achieve persistence.

**Comment by markstos** [comment]
I'm happy with the balance that text is persisted and basic rich media copy/paste works, as `--no-persist` offers.

**Comment by yory8** [comment]
I decided to give up on this.
